# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=256, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
