# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0008_remove_user_represent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a', '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a'), ('\u0421\u043f\u043e\u043d\u0441\u043e\u0440', '\u0421\u043f\u043e\u043d\u043e\u0441\u043e\u0440')], default='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a', max_length=15, verbose_name='\u0420\u043e\u043b\u044c'),
        ),
    ]
