# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20160608_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberconference',
            name='role',
            field=models.CharField(choices=[('listener', '\u0421\u043b\u0443\u0448\u0430\u0442\u0435\u043b\u044c'), ('reporter', '\u0414\u043e\u043a\u043b\u0430\u0434\u0447\u0438\u043a')], default='listener', max_length=15, verbose_name='\u0420\u043e\u043b\u044c'),
        ),
    ]
