# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20160608_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='representer',
            name='sponsor',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u0421\u043f\u043e\u043d\u0441\u043e\u0440'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representer',
            name='representer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
